# github workflow to deploy helloworld to azure

name: Build .NET application and deploy it to azure -- helloword

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Build
        run: dotnet build --configuration Release --no-restore